version: '2'

services:
  sqlinux:
    build:
      context: ./db
    ports:
      - 1433:1433
    volumes:
      - C://Temp:/var/opt/mssql/temp/
  api:
    build:
      context: ./api
    depends_on:
      - sqlinux
    ports:
      - 5000:5000
  web:
    build:
     context: ./web
    ports:
      - 4200:4200
